# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, verbose_name='Address')),
                ('valid', models.BooleanField(default=True, help_text='Identify if email is valid (still).', verbose_name='Is valid?')),
                ('default', models.BooleanField(default=True, help_text='Use this e-mail as primary for office', verbose_name='Default')),
            ],
            options={
                'verbose_name': 'E-mail address',
                'verbose_name_plural': 'E-mail addresses',
            },
        ),
    ]
