# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20160512_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='default',
        ),
    ]
