# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:41
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True)),
                ('visible', models.BooleanField(default=True, verbose_name='Verified')),
                ('postcode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Post code')),
                ('regon', models.CharField(blank=True, db_index=True, help_text='Compatible with National Official Register of National Economy Entities', max_length=10, null=True, verbose_name='REGON')),
                ('krs', models.CharField(blank=True, db_index=True, help_text='Compatible with Polish National Court Register', max_length=9, null=True, verbose_name='Registration number')),
                ('extra', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
    ]
