# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:45
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_bleach.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_mailbox', '0004_bytestring_to_unicode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_auto_20160512_1041'),
        ('offices', '0002_auto_20160512_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=b'letters/%Y/%m/%d', verbose_name='File')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='subject', unique=True, verbose_name='Slug')),
                ('content', django_bleach.models.BleachField()),
                ('quote', django_bleach.models.BleachField()),
                ('eml', models.FileField(blank=True, null=True, upload_to='eml_msg/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
            },
        ),
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('letter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='letters.Letter')),
                ('email', models.CharField(help_text='Field valid only for incoming messages', max_length=100, null=True, verbose_name='From e-mail')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_office', to='offices.Office')),
            ],
            options={
                'verbose_name': 'Incoming letter',
                'verbose_name_plural': 'Incoming letters',
            },
            bases=('letters.letter',),
        ),
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('letter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='letters.Letter')),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail address')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_letter', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.Office')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outgoing letter',
                'verbose_name_plural': 'Outgoing letters',
            },
            bases=('letters.letter',),
        ),
        migrations.AddField(
            model_name='letter',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
        migrations.AddField(
            model_name='letter',
            name='msg',
            field=models.ForeignKey(blank=True, help_text='Message registered by django_mailbox', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_mailbox.Message'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.Letter'),
        ),
    ]
